### PR TITLE
Refactor JSONAPI.View to Behaviour

### PR DESCRIPTION
**Pull request by lucacorti**
Hi guys,

This follows on #253 and refactors the `JSONAPI.View` module to a proper Elixir Behaviour.

This has a few benefits:

- Reduces the amount of code injected in view modules, this is important and credo was complaining/silenced
-  Moves most logic to standard functions in `JSONAPI.View`, enabling unit testing on these
- Clearly specifies the callbacks the view module expects to be implemented
- Provides compile time checking on callback functions, especially when using `@impl` annotations.
- Is, as expected, completely backwards compatible. As you can see, I didn't touch tests.

### CODE REVIEW

**Comment by jeregrine** [comment]
@lucacorti please handle the merge conflicts.

**Comment by snewcomer** [comment]
@lucacorti Mind merging in some minor changes from the main branch and then we can review together and merge?

**Comment by doomspork** [comment]
@lucacorti  @jeregrine  @snewcomer is this good to move forward? I no longer see merge conflicts?

**Review by jeregrine — APPROVED** [review]

**Comment by lucacorti** [comment]
Sorry, I was not able to chime in earlier. Thanks for merging, I've opened #263 to fix a bug introduced by this.

**Pull request merged**
